---
#####
# Survival Game Plugin
# Made By: Andre_The_Gamer
# Config: iawesomecreeper 
#####

########################
# Message
########################
PlayerJoinServer: Welcome To {Your Server Name}
ArenaJoin: Joinning a Hunger Game Arena
Arenajoined: You have join SG-1


########################################################
# Arena's #
########################################################
Lobby: Lobby    // This will be where everyone spawns after they die or win.
Arena: SG   // This will teleport the player to the arena

Min-Player: 2 // Minimum players cannot be changed 'YET"
Max-Player: 24 // Maximum players on the arena cannot be changed'YET"


# Stand Where you wan't the players to spawn in use /xyz and place them in Spawns
# Add The same line for more player's
Spawns:
- 12      // Edit the number's
- 121
- 121


---
